name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Generate a timestamp and store it in a variable
    - name: Generate Timestamp
      id: timestamp
      run: echo "::set-output name=timestamp::$(date +%s)"

    - name: Navigate to apps/api directory
      run: cd apps/api
    
    - name: List files in the current directory
      run: ls -alt

    - name: Build the Docker image
      run: |
        TIMESTAMP="${{ steps.timestamp.outputs.timestamp }}"
        docker build . --file worker.Dockerfile --tag 0001coder/coolcrawl-worker:${TIMESTAMP}
        docker tag 0001coder/coolcrawl-worker:${TIMESTAMP} 0001coder/coolcrawl-worker:latest

        docker build . --file server.Dockerfile --tag 0001coder/coolcrawl-server:${TIMESTAMP}
        docker tag 0001coder/coolcrawl-server:${TIMESTAMP} 0001coder/coolcrawl-server:latest

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to registry
      run: |
        TIMESTAMP="${{ steps.timestamp.outputs.timestamp }}"
        docker push 0001coder/coolcrawl-worker:${TIMESTAMP}
        docker push 0001coder/coolcrawl-worker:latest

        docker push 0001coder/coolcrawl-server:${TIMESTAMP}
        docker push 0001coder/coolcrawl-server:latest
